<style>
	/*    Generated by http://www.cssportal.com    */

/* @import url("reset.css");*/

p, h1 {
    padding: 10px;
}

#wrapper {
    margin: 0 auto;
    width: 1100px;
}

#header {
    float: left;
    height: 80px;
    width: 1100px;
    /*background: #353447;*/
    border-bottom: 2px solid black;
}

#footer {
    height: 50px;
    width: 1100px;
    clear: both;
}

</style>

<script>
	import Navigation from "./nav.svelte"
	import LeftColumn from "./leftColumn.svelte"
	import Content from "./content.svelte"
</script>

<div id="wrapper">
	<div id="header">
		<h1>Clicker Game</h1>
	</div>
	<Navigation />
	<LeftColumn />
	<Content />
	<div id="footer">
		<p>This is the Footer</p>
	</div>
</div>